Minimal Example fix for pid problem in process namespaces envs like containers or WSL2
libbpf/libbpf-bootstrap pull request #175
Opened 2023-05-01 02:40 UTC by unikzforce

Currently minimal example does not work in environments which are inside a process namespace, like docker containers or WSL2, because the pid of the `minimal` process inside the userspace is not equal to `tgid` of that process in the bpf.

this is the fix.

2023-05-01 02:57 UTC, unikzforce commented
Or maybe I should create another example side by side `minimal` like `minimal_container` so that `minimal` would remain untouched and simple and people also could learn how to prepare for namespace environment by seeing `minimal_container`.

wdyt?

2023-05-04 00:11 UTC, anakryiko commented
Yes, let's keep minimal as is, and add a new example demonstrating namespaced pid

2023-05-10 06:06 UTC, zouyonghao commented
This is so great as I just meet this issue with WSL2!

2023-05-13 03:58 UTC, unikzforce commented
Sorry guys, I was under heavy workload in my current job, I'll fix this PR very soon.

2023-05-14 00:58 UTC, unikzforce commented
@anakryiko could you please review again?

2023-05-16 18:19 UTC, anakryiko requested changes
Looks good overall, few nits in the comments.

But let's fix up commit formatting:
 - use "examples/c: " prefix in commit subject
 - it's probably to name commit something more like "add minimal_ns example demonstrating PID namespace translation"
 - Please fill out commit description, not just subject. It could be very minimal, but it has to be present.
 - Signed-off-by: tag requires full name to be used. I presume "unikzforce" is not your full name, right?

And yes, "minimal_namespaced" is pretty mouthful, let's shorten it to "minimal_ns"?

2023-05-16 18:19 UTC, anakryiko commented on README.md
> +`minimal` would not work in environments that have namespace, like containers, or WSL2,
see Minimal_Legacy below, let's keep each binary as a separate section?

2023-05-16 18:19 UTC, anakryiko commented on examples/c/minimal_namespaced.bpf.c
> +/* Copyright (c) 2020 Facebook */
update copyright year and company/author name?

2023-05-16 18:19 UTC, anakryiko commented on examples/c/minimal_namespaced.c
> +/* Copyright (c) 2020 Facebook */
ditto

2023-05-17 21:02 UTC, merged