examples/c: Build bpftool submodule in cmake
libbpf/libbpf-bootstrap pull request #73
Opened 2022-05-19 12:47 UTC by JackyYin

Ref: #70.

Because tools/bpftool no longer exists, we need to build bpftool from git submodule and set the correct executable path in cmake variable `BPFOBJECT_BPFTOOL_EXE`.

2022-05-19 13:32 UTC, JackyYin commented
BTW, seems like we can remove the `STEP_TARGETS` in `ExternalProject_Add` and this line also: `add_dependencies(${app_stem}_skel libbpf-build)` because libbpf always built before examples even if I remove these lines.

2022-05-25 01:24 UTC, JackyYin commented
Hello @anakryiko,
Could you give some suggestions about this PR?
I wonder what can I fix to get it merged.
Thanks a lot!

2022-05-25 04:29 UTC, anakryiko requested changes
I see this follows the approach for building libbpf so looks sane to me. Please fix the typo and can you also add Signed-off-by: with your full name and email just like libbpf/kernel commits have it? Thanks!

2022-05-25 04:29 UTC, anakryiko commented on examples/c/CMakeLists.txt
> +ExternalProject_Add(boftool
this should probably be `bpftool`, no?

2022-05-25 04:44 UTC, JackyYin commented on examples/c/CMakeLists.txt
> +ExternalProject_Add(boftool
Fixed.
Sorry for the typo.

2022-05-25 04:49 UTC, JackyYin commented
> I see this follows the approach for building libbpf so looks sane to me. Please fix the typo and can you also add Signed-off-by: with your full name and email just like libbpf/kernel commits have it? Thanks!

Thanks for your feedback!
I just fixed the typo and added the `Signed-off-by` to my commit message.
The commit is squashed and force-pushed back again.

2022-05-25 04:56 UTC, anakryiko approved these changes

2022-05-25 04:57 UTC, merged

2022-05-25 04:57 UTC, anakryiko commented
Thanks!

2022-05-26 22:13 UTC, danobi commented
lgtm